baseURL: "https://microshift.io"
title: MicroShift.io
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
GoogleAnalytics:

minify:
  disableXML: true
  minifyOutput: true

params:
  # mainSections: blog
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: MicroShift.io
  description: "Optimized OpenShift Kubernetes for small form factor and Edge Computing"
  # keywords: [Blog]
  author: MicroShift.io Team
  # author: ["Me", "You"] # multiple authors
  # images: ["/mylogo.svg"]
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  searchHidden: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  label:
    text: "Home"
    # icon: /apple-touch-icon.png
    iconHeight: 35

  # home-info mode
  homeInfoParams:
    Title: "Hi!"
    Content: Welcome to MicroShift documentation site

  # analytics:
  #   google:
  #     SiteVerificationTag: ""
  #   yandex:
  #     SiteVerificationTag: ""

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: home 
      name: Home
      url: index.html
      weight: 20
    - identifier: design
      name: Design
      url: /content/design/design.md
      weight: 20
    - identifier: microshift-aio
      name: MicroShift AIO
      url: /content/microshift-aio/README.md
      weight: 30
    - identifier: microshift-containerized
      name: MicroShift Containerized
      url: /content/microshift-containerized/README.md
      weight: 40
    - identifier: known-issues
      name: Known Issues
      url: /content/known-issues.md
      weight: 50


outputs:
  home: ["HTML", "RSS", "JSON"]
  page: ["HTML", "RSS"]

sitemap:
  changefreq: "monthly"
  filename: "sitemap.xml"
  priority: 0.5
