baseURL = "https://microshift.io"
languageCode = "en-us"
title = "MicroShift.io"
themesDir = "themes"
theme = "hugo-whisper-theme"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 300

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/docs/"
    weight = 2

[[menu.main]]
    name = "Design"
    url = "/docs/design/design"
    weight = 3

[[menu.main]]
    name = "DeploymentModes"
    url = "/docs/deployment-modes/"
    weight =4

[[menu.main]]
    name = "Operations"
    url = "/docs/operations/"
    weight = 5

[[menu.main]]
    name = "LocalDevelopment"
    url = "/docs/local-development/local-development"
    weight = 6

[[menu.main]]
    name = "Community"
    url = "/docs/community/community"
    weight = 7

[params]
  google_analytics_id=""
  homepage_button_link = '/docs'
  homepage_button_text = 'Read The Docs'
  homepage_intro = 'MicroShift is a research project that is exploring how OpenShift and Kubernetes can be optimized for small form factor and edge computing.'
  homepage_image = '/images/microshift.gif'

  ## You can enable to add anchor links to header elements
  # enable_anchor_link = true

  [params.homepage_meta_tags]
    meta_description = "MicroShift is a research project that is exploring how OpenShift and Kubernetes can be optimized for small form factor and edge computing."
    meta_og_title = "MicroShift"
    meta_og_type = "website"
    meta_og_url = "https://microshift.io"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-whisper-theme/master/images/tn.png"
    meta_og_description = "MicroShift is a research project that is exploring how OpenShift and Kubernetes can be optimized for small form factor and edge computing."
    meta_twitter_card = "summary"
    meta_twitter_site = "@microshift"
    meta_twitter_creator = "@microshift"

  [params.logo]
      mobile = "/images/logo-mobile.svg"
      standard  = "/images/logo.svg"
